#!/bin/bash

#checking and installing Backports

pack="backports"
I=dpkg -s $pack | grep "Status"
if [ -n "$I" ]
then
   echo $1" installed"
else
   echo $1" not installed,try to install"
   cd /etc/apt/sources.list.d/
   sudo touch backports.list
   sudo echo "deb http://deb.debian.org/debian bullseye-backports main contrib non-free" | sudo tee -a /etc/apt/sources.list 
   sudo echo "deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free" | sudo tee -a /etc/apt/sources.list
fi

#refreshing packet manager

sudo apt-get update

#installing and launching Apache2

sudo apt install apache2 
sudo systemctl start apache2

#installing Python 3.9

sudo apt install python3.9

#installing openssh-server and launching ssh

sudo apt install openssh-server
sudo systemctl start ssh

#get to know the weather in Moscow for 3 today next 2 days

sudo curl -3 wttr.in/Moscow

#get to know OS and its version

uname -v

#Creating new python file and getting

sudo touch test.py
echo "print(Hello world!)" > test.py
sudo chmod +x test.py

#Checking root user

ROOT_UID=0

if [ "$UID" -eq "$ROOT_UID" ]
then
echo "Great! You are a root user"
else
echo "You are not the root user"
fi

#Cleaning log files

LOG_DIR=/var/log
cd $LOG_DIR

cat /dev/null > messages
cat /dev/null > wtmp

#Back up the files and directories that were updated in the last 24 hours

BACKUPFILE=backup-$(date +%m-%d-%Y)
archive=${1:-$BACKUPFILE}

find . -mtime -1 -type f -print0 | xargs -0 tar rvf "$archive.tar"
echo "$PWD backed up in archive file \"$archive.tar.gz\"."
exit 0